#базовый файл настроек django проекта для работы с api, auth и медиа
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

#считаем корневую директорию проекта относительно текущего файла
BASE_DIR = Path(__file__).resolve().parent.parent


#настройки для локальной разработки, не стоит использовать в продакшене
SECRET_KEY = 'django-insecure-+a^q6=77tb+s^jtu7wj2-sr63knui4&t&uk061v0zu)vw9l7&l'
DEBUG = True
ALLOWED_HOSTS = []


#список установленных приложений django и сторонних библиотек проекта
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #сторонние библиотеки для api и документации
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    #локальные приложения проекта
    'users',
    'store',
    'cart',
    'orders',
]

#подключаем middleware для cors, сессий, безопасности и auth
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

#разрешаем cors для запросов с фронтенда
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


#настройки подключения к базе postgres для хранения данных проекта
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'flower_shop_db',
        'USER': 'postgres',
        'PASSWORD': 'Sch4911D04!',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


#настройки проверки пароля для безопасности регистрации и входа
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#языковые настройки проекта
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


#настройки статических файлов для frontend и административной панели
STATIC_URL = 'static/'


#настройки отправки email в локальной разработке через консоль
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

#подключаем кастомную модель пользователя из приложения users
AUTH_USER_MODEL = 'users.User'

#настройки rest framework и jwt для api авторизации
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

#настройки документации swagger и openapi для удобного тестирования api
SPECTACULAR_SETTINGS = {
    'TITLE': 'Flower Shop API',
    'DESCRIPTION': 'REST API для интернет-магазина цветов (Курсовой проект)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'BearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'Введите JWT токен в формате: Bearer <ваш_токен>'
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}

from datetime import timedelta

#настройки времени жизни access и refresh токенов
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

#настройки папки для хранения изображений товаров и медиафайлов
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'